dist: trusty
sudo: required
services:
  - docker

branches:
  only:
    - master
    - /^release\-.+/

script:
  - mntdir='/mnt/opendesktop-app'
  - docker run --rm -v $(pwd):${mntdir} ubuntu:14.04 /bin/bash -c "${mntdir}/scripts/package ci_appimage"
  - cat transfer.log
