#!/bin/bash

PKGNAME='ocs-store'
PKGVER='4.0.1'
PKGREL='1'

UPDINFO='zsync|http://dl.opendesktop.org/api/files/download/id/1532435039/as/latest/ocs-store-x86_64.AppImage.zsync'
APPDIR="${PKGNAME}.AppDir"

make
make DESTDIR=${APPDIR} prefix=/usr install

install -D -m 755 ${APPDIR}/usr/bin/${PKGNAME} ${APPDIR}/AppRun
install -D -m 644 ${APPDIR}/usr/share/applications/${PKGNAME}.desktop ${APPDIR}/${PKGNAME}.desktop
install -D -m 644 ${APPDIR}/usr/share/icons/hicolor/scalable/apps/${PKGNAME}.svg ${APPDIR}/${PKGNAME}.svg

install -D -m 755 /usr/lib/x86_64-linux-gnu/libgconf-2.so.4 ${APPDIR}/usr/lib/ocs-store-linux-x64/libgconf-2.so.4
install -D -m 755 /usr/lib/x86_64-linux-gnu/libXss.so.1 ${APPDIR}/usr/lib/ocs-store-linux-x64/libXss.so.1
install -D -m 755 /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libcanberra-gtk-module.so ${APPDIR}/usr/lib/ocs-store-linux-x64/libcanberra-gtk-module.so
install -D -m 755 /usr/lib/x86_64-linux-gnu/libgnome-keyring.so.0 ${APPDIR}/usr/lib/ocs-store-linux-x64/libgnome-keyring.so.0

install -D -m 644 launcher/imwheelrc ${APPDIR}/etc/imwheelrc
install -D -m 644 /etc/X11/Xsession.d/60imwheel_start-imwheel ${APPDIR}/etc/X11/Xsession.d/60imwheel_start-imwheel
install -D -m 644 /etc/X11/imwheel/imwheelrc ${APPDIR}/etc/X11/imwheel/imwheelrc
install -D -m 644 /etc/X11/imwheel/startup.conf ${APPDIR}/etc/X11/imwheel/startup.conf
install -D -m 755 /usr/bin/imwheel ${APPDIR}/usr/bin/imwheel
#install -D -m 755 /usr/lib/imwheel/getmdt ${APPDIR}/usr/lib/imwheel/getmdt
#install -D -m 755 /usr/lib/imwheel/mdetect ${APPDIR}/usr/lib/imwheel/mdetect
#install -D -m 755 /usr/lib/imwheel/mdump ${APPDIR}/usr/lib/imwheel/mdump
#install -D -m 755 /usr/lib/imwheel/mice/a4tech ${APPDIR}/usr/lib/imwheel/mice/a4tech
#install -D -m 755 /usr/lib/imwheel/mice/default ${APPDIR}/usr/lib/imwheel/mice/default
#install -D -m 755 /usr/lib/imwheel/mice/intellimouse ${APPDIR}/usr/lib/imwheel/mice/intellimouse
#install -D -m 755 /usr/lib/imwheel/mice/mouseman+ ${APPDIR}/usr/lib/imwheel/mice/mouseman+
#install -D -m 755 /usr/lib/imwheel/mice/netmouse ${APPDIR}/usr/lib/imwheel/mice/netmouse
#install -D -m 755 /usr/lib/imwheel/see ${APPDIR}/usr/lib/imwheel/see
#install -D -m 755 /usr/lib/imwheel/setimps2 ${APPDIR}/usr/lib/imwheel/setimps2
#install -D -m 755 /usr/lib/imwheel/setmmplus ${APPDIR}/usr/lib/imwheel/setmmplus

curl -fsSL -o ocs-manager https://git.opendesktop.org/akiraohgaki/ocs-manager/uploads/ebf99a67dcd30bc57cfa371cac1f959e/ocs-manager-0.7.2-1-x86_64.AppImage
install -D -m 755 ocs-manager ${APPDIR}/usr/bin/ocs-manager

curl -fsSL -o appimagetool https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
chmod 755 appimagetool
./appimagetool --appimage-extract
./squashfs-root/AppRun -u "${UPDINFO}" ${APPDIR}

mv *-x86_64.AppImage ../${PKGNAME}-${PKGVER}-${PKGREL}-x86_64.AppImage
