#!/bin/bash

PKGNAME='ocs-store'

PKGUSER='pkgbuilder'

PKGSCRIPT="${0}"

PROJDIR="$(cd "$(dirname "${0}")/../" && pwd)"

BUILDDIR="${PROJDIR}/build_${PKGNAME}"

appimage() { # docker-image: ubuntu:14.04
    install_build_deps_appimage
    add_pkguser
    su -c "export HOME=/home/${PKGUSER} && "${PKGSCRIPT}" build_appimage" ${PKGUSER}
    transfer_file "$(find "${BUILDDIR}" -type f -name "${PKGNAME}*-x86_64.AppImage")"
}

install_build_deps_appimage() {
    apt update -qq
    apt -y install curl git
    apt -y install build-essential
    log="$(git clone https://github.com/tj/n.git -b master --single-branch --depth=1 "${PROJDIR}/n" \
        && cd "${PROJDIR}/n" \
        && make install \
        && rm -rf "${PROJDIR}/n" \
        && n lts)"
    echo "${log}"
    apt -y install libgconf-2-4 libxss1 libcanberra-gtk-module libgnome-keyring0
}

build_appimage() {
    rm -rf "${BUILDDIR}"
    mkdir -p "${BUILDDIR}"
    export_srcarchive "${BUILDDIR}/${PKGNAME}.tar.gz"
    tar -xzf "${BUILDDIR}/${PKGNAME}.tar.gz" -C "${BUILDDIR}"
    cp "${PROJDIR}/pkg/appimage/appimagebuild" "${BUILDDIR}/${PKGNAME}"
    cd "${BUILDDIR}/${PKGNAME}"
    ./appimagebuild
}

add_pkguser() {
    useradd -m ${PKGUSER}
    chown -R ${PKGUSER} "${PROJDIR}"
}

export_srcarchive() {
    if [ "${1}" ]; then
        log="$(cd "${PROJDIR}" && git archive --prefix="${PKGNAME}/" --output="${1}" HEAD)"
    fi
}

transfer_file() {
    if [ -f "${1}" ]; then
        filename="$(basename "${1}")"
        transferlog="${PROJDIR}/transfer.log"
        echo "Uploading ${filename}" >> "${transferlog}"
        curl -fsSL -T "${1}" "https://transfer.sh/${filename}" >> "${transferlog}"
        echo '' >> "${transferlog}"
    fi
}

if [ "${1}" ]; then
    ${1}
fi
